config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  as :user do
    get "login", to: "users/sessions#new", as: :user_login
    delete "logout", to: "devise/sessions#destroy", as: :user_logout
    get "registration", to: "users/registrations#new", as: :account_registration
  end

  resources :blogs, only: [ :show, :index ] do
    resources :comments, only: [ :create ]
  end

  root to: "home#index"
  get "/sitemap", to: "home#sitemap"
  get "/promo/:q/products", to: "products#index", as: :promotion_products
  post :email_subscription, to: "public#subscribe"
  resources :wishlists, only: [ :index, :destroy ]
  resources :products do
    post :review
    resources :wishlists, only: [ :create ]
    get :quickview
    get :compare
    get :remove_compare
    collection do
    end
  end

  resources :orders, except: [ :index, :new, :create, :destroy ] do
    post :populate, on: :collection
    get :reset, on: :collection
    get :shipped_track
  end

  resources :feedbacks, only: [ :new, :create ]

  get "/c/*id", to: "categories#show", as: :categories
  get "/b/*id", to: "products#brand_show", as: :brands

  resources :carts
  post "/checkout/update_coupon_code", to: "checkout#update_coupon_code"
  get "/checkout", to: "checkout#edit", as: :cart_checkout
  get "/checkout/:state", to: "checkout#edit", as: :checkout_state
  patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout

  post "/paypal", to: "paypal#express", as: :paypal_express
  get "/paypal/confirm", to: "paypal#confirm", as: :confirm_paypal
  get "/paypal/cancel", to: "paypal#cancel", as: :cancel_paypal
  get "/paypal/notify", to: "paypal#notify", as: :notify_paypal

  post "/ssl_commerz", to: "ssl_commerz#ssl_express", as: :ssl_express
  post "/ssl_commerz/confirm", to: "ssl_commerz#confirm", as: :confirm_ssl
  post "/ssl_commerz/cancel", to: "ssl_commerz#cancel", as: :cancel_ssl
  post "/ssl_commerz/failed", to: "ssl_commerz#failed", as: :failed_ssl

  namespace :admin do
    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
        get :login
      end

      collection do
        get :customer
        get :supplier
      end
      resources :store_credits
    end
    resources :print_barcodes do
      collection do
        get :preview
      end
    end
    resources :feedbacks do
      member do
        post :checked_feedback
      end
    end
    resources :contacts do
      member do
        post :checked_query
      end
      collection do
        get :check_order
      end
    end
    get "/subscribers", to: "dashboard#subscribers"
    get "/reports", to: "dashboard#monthly_reports"
    get "/purchase_reports", to: "dashboard#purchase_reports"
    get "/sales_reports", to: "dashboard#sales_reports"
    namespace :suppliers do
      get "/purchase/orders", to: "purchase_orders#index", as: :purchases
      resources :purchase_orders do
        member do
          get :cart
          post :add_item
          get :complete
          post :update_item
          post :update_receive_item
          post :update_purchase
          post :remove_item
          post :remove_receive_item
          get :receive
          post :received_purchase
        end
        collection do
          get :refunds
          get :new_order
          get :refund
          get :new_refund_items
          post :return_item
        end
      end
      post "process_invoice"
      resources :refunds do
        collection do
          get :new_refund
          get :refund
          get :refund_items
          get :edit_refund
          delete :remove_refund_item
          post :new_return_item
          post :update_refund
          delete :remove_refund
        end
      end
      resources :payments do
        get :complete, on: :member
        get :confirm, on: :member
        get :bounce, on: :member
        get :rescheduled, on: :member
        get :download, on: :collection
        get :commission_report, on: :collection
      end
      resources :invoices do
        get "details"
        get "history"
      end
      resources :discounts
      resources :text_messages
    end

    resources :suppliers do
      member do
        get :address
        put :address
        get :orders
        get :get_history
        get :statement
      end
      collection do
        get "purchase_list", to: "suppliers#purchase_list"
        get "supplier_balance", to: "suppliers#supplier_balance"
      end
    end
    resources :prints
    resources :categories
    resources :brands
    resources :gallery_images
    resources :products do
      member do
        get :stock
        get :review
        delete :remove_review
        put :approved
      end
      collection do
        get :inventory
        get :purchase_product_search
        get :reorder_leveled
        get :name_search
      end
      resources :images
      resources :variants
    end
    resources :blogs do
      resources :comments, only: [ :destroy, :edit, :update ]
    end
    resources :home_sliders
    resources :coupons
    resources :shipping_methods

    resources :payment_methods

    resources :stock_locations do
      member do
        get :stock_items
      end
      resources :stock_movements
    end
    resources :stock_items
    resources :stock_transfers
    get :shipment_tracking, to: "orders#shipment_tracking"

    resources :orders, except: [ :show ] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        post :add_product
        post :shipment
        post :update_line_item
        post :remove_line_item
      end
      collection do
        get :new_orders
        get :drafts
      end

      resources :state_changes, only: [ :index ]

      resource :customer, controller: "orders/customers"
      resources :customer_returns, only: [ :index, :new, :edit, :create, :update ] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [ :new, :create, :edit, :update ]
      end

      resources :reimbursements, only: [ :index, :create, :show, :edit, :update ] do
        member do
          post :perform
        end
      end
    end
  end
  get "/admin", to: "admin/dashboard#index", as: :admin
  get "/admin/orders/:id/tracks", to: "admin/orders#track", as: :admin_order_track
  patch "/admin/order/:id/update_state/", to: "admin/orders#update_state", as: :order_state

  resources :contacts, only: [ :new, :create ]
  get "/frequently-asked-question", to: "public#faq", as: :faq
  get "/secure_shopping", to: "public#secure_shopping", as: :secure_shopping
  get "/coupon-code", to: "public#coupon", as: :coupon
  get "/return-policy", to: "public#return_policy", as: :return_policy
  get "/our-promise", to: "public#promise", as: :our_promise
  match "/dedicated-customer-support", to: "public#contact_us", via: [ :get, :post ], as: :contact_us
  get "/free-shipping-worldwide", to: "public#international", as: :international
  get "/safe_shopping_guarantee", to: "public#safe_shopping_guarantee", as: :safe_shopping_guarantee
  get "/about_us", to: "public#about_us", as: :about_us
  get "/privacy_policy", to: "public#privacy_policy", as: :privacy_policy
  get "/term_condition", to: "public#term_condition", as: :term_condition
  get "/my_account", to: "users#my_account"
  get "/cart", to: "public#cart"
  get "/p_checkout", to: "public#checkout"
  post "/email_subscription", to: "public#subscribe"
  post "/checkout", to: "checkout#check_coupon_code"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users
      get "home", to: "home#index"
      get "my_account", to: "users#my_account"
      resources :products, only: [ :index, :show ] do
        get "filters", on: :collection
        get "get_names", on: :collection
      end
      resources :wishlists, only: [ :index, :create ] do
        get :remove
      end
      resources :contacts, only: [ :create ]
      resources :orders, only: [ :index, :update, :show ] do
        post :populate, on: :collection
        post :current_cart, on: :collection
        post :detail, on: :collection
        post :current_state, on: :collection
        post :update_address, on: :collection
        post :update_order, on: :collection
        post :get_ship_address, on: :collection
        post :get_shipments, on: :collection
        post :get_payment_info, on: :collection
      end
      resources :reviews, only: [ :index, :create, :update, :destroy ]
      resources :shipments, only: [ :create, :update ] do
        member do
          put :ship
        end
      end
      resources :line_items do
        post :remove_item, on: :collection
      end

      post "/checkout/update_order/:state", to: "checkout#update_order", as: :update_checkout
    end
  end
end

app/models/admin/suppliers.rb
module Admin::Suppliers
  def self.table_name_prefix
    'admin_suppliers_'
  end
end

app/models/admin/suppliers/discount.rb
# == Schema Information
#
# Table name: admin_suppliers_discounts
#
#  id              :integer          not null, primary key
#  amount          :integer
#  date            :date
#  discount_by     :string
#  discount_reason :string
#  invoice_no      :string
#  invoice_id      :integer
#  supplier_id     :integer
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_admin_suppliers_discounts_on_supplier_id  (supplier_id)
#

class Admin::Suppliers::Discount < ApplicationRecord
  validates :supplier_id, :amount, :date, presence: true

  belongs_to :supplier, class_name: 'User'
  belongs_to :invoice, class_name: 'Admin::Suppliers::Invoice'
end

app/models/admin/suppliers/invoices.rb
module Admin::Suppliers::Invoices
  def self.table_name_prefix
    'admin_suppliers_invoices_'
  end
end

app/models/admin/suppliers/invoices/attachment.rb
# == Schema Information
#
# Table name: admin_suppliers_invoices_attachments
#
#  id         :integer          not null, primary key
#  invoice_id :integer
#  picture    :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Admin::Suppliers::Invoices::Attachment < ApplicationRecord
  mount_uploader :picture, SupplierInvoiceUploader
  belongs_to :invoice , class_name: 'Admin::Suppliers::Invoice'
end

app/models/admin/suppliers/text_message.rb
# == Schema Information
#
# Table name: admin_suppliers_text_messages
#
#  id          :integer          not null, primary key
#  supplier_id :integer
#  employee_id :integer
#  content     :text
#  direction   :string
#  read        :boolean
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Admin::Suppliers::TextMessage < ApplicationRecord
end

app/controllers/admin/suppliers/discounts_controller.rb
module Admin
  module Suppliers
    class DiscountsController < BaseController
      before_action :set_admin_suppliers_discount, only: [:show, :edit, :destroy]

      # GET /admin/suppliers/discounts
      # GET /admin/suppliers/discounts.json
      def index
        @discounts = Admin::Suppliers::Discount.all.order(created_at: :desc)
        @discounts = @discounts.page(params[:page]).per(20)
      end

      # GET /admin/suppliers/discounts/1
      # GET /admin/suppliers/discounts/1.json
      def show
      end

      # GET /admin/suppliers/discounts/new
      def new
        @invoices = Admin::Suppliers::Invoice.invoices
        @invoice = @invoices.find_by_id(params[:invoice_id]) if params[:invoice_id]
        p @invoice
        @discount = Admin::Suppliers::Discount.new(invoice_id: @invoice.id) if @invoice
      end

      # GET /admin/suppliers/discounts/1/edit
      def edit
      end

      # POST /admin/suppliers/discounts
      # POST /admin/suppliers/discounts.json
      def create

        @invoice = Admin::Suppliers::Invoice.find_by_id(discount_params[:invoice_id])
        @discount = @invoice.discounts.build(discount_params.merge(supplier_id: @invoice.supplier_id))
        if @discount.save
          if @invoice.due_amount <= 0
            @invoice.is_complete = true
          else
            @invoice.is_complete = false
          end
          @invoice.save
          redirect_to admin_suppliers_discounts_path
        else
          @discount.errors
          render :new, invoice_id: @invoice.id
        end
      end

      # PATCH/PUT /admin/suppliers/discounts/1
      # PATCH/PUT /admin/suppliers/discounts/1.json
      def update
        @invoice = Admin::Suppliers::Invoice.find_by_id(discount_params[:invoice_id])
        @discount = @invoice.discounts.find_by_id(params[:id])
        @discount.update(discount_params.merge(supplier_id: @invoice.supplier_id))
        if @discount.save
          redirect_to admin_suppliers_discounts_path
        end
      end

      # DELETE /admin/suppliers/discounts/1
      # DELETE /admin/suppliers/discounts/1.json
      def destroy
        @discount.destroy
        respond_to do |format|
          format.html { redirect_to admin_suppliers_discounts_url, notice: 'Discount was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_suppliers_discount
        @discount = Admin::Suppliers::Discount.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def discount_params
        params.require(:admin_suppliers_discount).permit(:amount, :date, :discount_by, :discount_reason, :invoice_no, :invoice_id, :supplier_id)
      end
    end
  end
end

app/controllers/admin/suppliers/invoices_controller.rb
module Admin
  module Suppliers
    class InvoicesController < BaseController
        before_action :set_admin_suppliers_invoice, only: [:show, :edit, :update, :destroy]

      # GET /admin/suppliers/invoices
      # GET /admin/suppliers/invoices.json
      def index
        @suppliers_invoices = Admin::Suppliers::Invoice.all.order(created_at: :desc)
        @suppliers_invoices = @suppliers_invoices.page(params[:page]).per(20)
      end

      # GET /admin/suppliers/invoices/1
      # GET /admin/suppliers/invoices/1.json
      def show
      end

      # GET /admin/suppliers/invoices/new
      def new
        @suppliers_invoice = Admin::Suppliers::Invoice.new
        @suppliers_invoice.attachments.build
      end

      # GET /admin/suppliers/invoices/1/edit
      def edit
      end

      # POST /admin/suppliers/invoices
      # POST /admin/suppliers/invoices.json
      def create
        @suppliers_invoice = Admin::Suppliers::Invoice.new(admin_suppliers_invoice_params)

        respond_to do |format|
          if @suppliers_invoice.save
            format.html { redirect_to @suppliers_invoice, notice: 'Invoice was successfully created.' }
            format.json { render :show, status: :created, location: @suppliers_invoice }
          else
            format.html { render :new }
            format.json { render json: @suppliers_invoice.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /admin/suppliers/invoices/1
      # PATCH/PUT /admin/suppliers/invoices/1.json
      def update
        respond_to do |format|
          if @suppliers_invoice.update(admin_suppliers_invoice_params)
            format.html { redirect_to @suppliers_invoice, notice: 'Invoice was successfully updated.' }
            format.json { render :show, status: :ok, location: @suppliers_invoice }
          else
            format.html { render :edit }
            format.json { render json: @suppliers_invoice.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /admin/suppliers/invoices/1
      # DELETE /admin/suppliers/invoices/1.json
      def destroy
        @suppliers_invoice.destroy
        respond_to do |format|
          format.html { redirect_to admin_suppliers_invoices_url, notice: 'Invoice was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      def history
        @invoice = Admin::Suppliers::Invoice.find_by_id(params[:invoice_id])
      end

      def details
        @invoice = Admin::Suppliers::Invoice.find_by_id(params[:invoice_id])
        render layout: false
      end
      private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_suppliers_invoice
        @suppliers_invoice = Admin::Suppliers::Invoice.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_suppliers_invoice_params
        params.require(:admin_suppliers_invoice).permit(:supplier_id, :no, :amount, :date, :transport_cost, attachments_attributes: [:id, :picture, :_destroy])
      end
    end
  end
end

app/helpers/admin/suppliers/discounts_helper.rb
module Admin::Suppliers::DiscountsHelper
end

app/helpers/admin/suppliers/invoices_helper.rb
module Admin::Suppliers::InvoicesHelper
end

app/helpers/admin/suppliers/payments_helper.rb
module Admin::Suppliers::PaymentsHelper
end

app/views/admin/suppliers/invoices/_details_of_order_invoice.html.erb
<div class="row">
  <div class="col-sm-7">
    <div class="panel panel-default">
      <div class="panel-heading">
        <div class="row">
          <div class="col-sm-6">
            <h4 class="panel-title title-padding-lg"><b>Supplier:</b></h4>
          </div>
          <div class="col-sm-6" style="margin-top: 8px;">
          </div>
        </div>
      </div>
      <% if @suppliers_invoice.supplier.present? %>
        <%= render 'admin/suppliers/supplier_info', supplier: @suppliers_invoice.supplier %>
      <% else %>
        <p>Unknown Supplier</p>
      <% end %>
    </div>
  </div>

  <div class="col-sm-5">
    <%= render 'admin/suppliers/invoice_general_info', invoice: @suppliers_invoice %>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default jobs-board product-barcodes">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            <h4 class="panel-title title-padding-lg">Order Items</h4>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <table class="table">
          <thead>
          <tr>
            <th>Image</th>
            <th>Code</th>
            <th>Name</th>
            <th>Stock</th>
            <th>Price</th>
            <th>Order Qty</th>
            <th>Received Qty</th>
            <th>Profit(%)</th>
            <th>Total</th>
            <th colspan="2"></th>
          </tr>
          </thead>
          <tbody id="pos-sales-products-tbody">
          <% @suppliers_invoice.items.each do |item| %>
            <%= render 'admin/suppliers/invoice_item_row', item: item %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12">
    <div class="panel panel-default jobs-board product-barcodes">
      <div class="panel-heading">
        <div class="row">
          <div class="col-md-12">
            <h4 class="panel-title title-padding-lg">Order Refund Items</h4>
          </div>
        </div>
      </div>
      <div class="panel-body">
        <div>
          <label>Refund Reason: </label>
          <span class="refund-reason"><%= @suppliers_invoice.order_refund.refund_reason if  @suppliers_invoice.order_refund.present? %></span>
        </div>
        <table class="table">
          <thead>
          <tr>
            <th>Image</th>
            <th>Code</th>
            <th>Name</th>
            <th>Return Date</th>
            <th> Amount</th>
            <th>created Date</th>
            <th></th>
          </tr>
          </thead>
          <tbody id="pos-sales-return-tbody">
          <% if @suppliers_invoice.order_refund.present? %>
            <% @suppliers_invoice.order_refund.items.each do |item| %>
              <%= render 'admin/suppliers/refunded_item', item: item %>
            <% end %>
          <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<%= render 'admin/suppliers/invoice_summary', invoice: @suppliers_invoice %>

app/views/admin/suppliers/invoices/_form.html.erb
<div data-hook="admin_user_form_fields" class="row">
  <div class="col-md-6">
    <%= f.field_container :supplier_id, class: ['form-group'] do %>
      <%= f.label :supplier_id, t(:suppliers) %>
      <%= f.select :supplier_id, User.suppliers.map{|c| [c.name, c.id]}, {prompt: "Select One"}, :class => "form-control", id: 'supplier_id' %>
      <%= f.error_message_on :supplier_id %>
    <% end %>

    <%= f.field_container :no, class: ['form-group'] do %>
      <%= f.label :no, t(:no) %>
      <%= f.text_field :no, :class => 'form-control' %>
      <%= f.error_message_on :no %>
    <% end %>
  </div>

  <div class="col-md-6">
    <%= f.field_container :amount, class: ['form-group'] do %>
      <%= f.label :amount, t(:amount) %>
      <%= f.number_field :amount, min: 0, :class => 'form-control' %>
      <%= f.error_message_on :amount %>
    <% end %>

    <%= f.field_container :transport_cost, class: ['form-group'] do %>
      <%= f.label :transport_cost, t(:transport_cost) %>
      <%= f.number_field :transport_cost, min: 0, :class => 'form-control' %>
      <%= f.error_message_on :transport_cost %>
    <% end %>
  </div>
  <div class="col-md-6">
    <%= f.field_container :date, class: ['form-group'] do %>
      <%= f.label :date, t(:date) %>
      <%= f.date_select :date, {}, :class => "form-control date"%>
      <%= f.error_message_on :date %>
    <% end %>
    <%= f.field_container :attachments, class: ['form-group'] do %>
      <%= f.fields_for :attachments do |ff| %>
        <%= ff.label :picture, t(:picture) %>
        <%= ff.file_field :picture, :class => "form-control" %>
      <% end %>
    <% end %>
  </div>



</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#supplier_id').select2();
    });
</script>

app/views/admin/suppliers/invoices/details.html.erb
<div class="customer-invoice-details">
  <table class="table table-borderless">
    <thead class="panel-heading">
    <tr>
      <th colspan="2" class="success text-center"> Supplier Invoice Details</th>
    </tr>
    </thead>
    <tbody>
    <tr>
      <td> Invoice No</td>
      <td> <%= @invoice.id %> </td>
    </tr>
    <tr>
      <td> Supplier</td>
      <td> <%= link_to @invoice.supplier.name, admin_supplier_path(@invoice.supplier_id) %> </td>
    </tr>
    <tr>
      <td> Amount</td>
      <td> <%= @invoice.amount %> </td>
    </tr>
    <tr>
      <td> Invoice Date</td>
      <td> <%= @invoice.date.strftime('%B %d, %Y') %> </td>
    </tr>
    <tr>
      <td> Due</td>
      <td> <%= @invoice.due_amount %> </td>
    </tr>
    </tbody>
  </table>
</div>

app/views/admin/suppliers/invoices/edit.html.erb
<% content_for :page_title do %>
  <%= link_to "Suppliers", admin_suppliers_path %> /
  <%= link_to "Invoices", admin_suppliers_invoices_path %> /
  <%= @suppliers_invoice.no %>
<% end %>

  <div class="panel-body">
    <div data-hook="admin_user_edit_form_header">
      <%= render partial: 'admin/shared/error_messages', locals: {target: @suppliers_invoice} %>
    </div>

    <div data-hook="admin_user_edit_form">
      <%= form_for [:admin, @suppliers_invoice], url: admin_suppliers_invoice_path(@suppliers_invoice), method: :put do |f| %>
        <%= render partial: 'form', locals: {f: f} %>

        <div data-hook="admin_user_edit_form_button">
          <%= render 'admin/shared/form_actions', record: f.object, cancel: admin_suppliers_invoices_path %>
        </div>
      <% end %>
    </div>
  </div>

<%#= render 'admin/users/lifetime_stats' %>

app/views/admin/suppliers/invoices/index.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  Invoices
<% end %>
<% content_for :page_actions do %>
  <%= render "admin/shared/supplier_links"  %>
<% end %>
<table class="table">
  <thead>
  <tr>
    <th>Supplier</th>
    <th>Invoice No</th>
    <th>Amount</th>
    <th>Transport_cost</th>
    <th>Invoice Date</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <% @suppliers_invoices.each do |invoice| %>
    <tr>
      <td>
        <%= link_to invoice.supplier.name, edit_admin_supplier_path(invoice.supplier) if invoice.supplier.present? %>
      </td>
      <td><%= invoice.no %></td>
      <td><%= invoice.amount %></td>
      <td> <%= invoice.transport_cost %> </td>
      <td> <%= I18n.localize(invoice.date, format: :long) %>
      </td>
      <td>
        <%= link_to 'Show', invoice %>
      </td>
      <td>
        <%= link_to 'Edit',invoice.is_order ? cart_admin_suppliers_purchase_order_path(id: invoice.id) : edit_admin_suppliers_invoice_path(invoice) %>
      </td>
      <td><%= link_to 'Destroy', invoice, method: :delete, data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
  <tbody>

  </tbody>
</table>
<%= paginate @suppliers_invoices, theme: 'twitter-bootstrap-4' %>

app/views/admin/suppliers/invoices/new.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  <%= link_to t(:invoices), admin_suppliers_invoices_path %> /
  <%= "New Invoice" %>
<% end %>

<% content_for :page_actions do %>
  <%= render "admin/shared/supplier_links"  %>
<% end %>
<div data-hook="admin_user_new_form_header">
  <%= render :partial => 'admin/shared/error_messages', :locals => {:target => @suppliers_invoice} %>
</div>

<div data-hook="admin_user_new_form">
  <%= form_for [:admin, @suppliers_invoice], url: admin_suppliers_invoices_url, method: :post do |f| %>
    <%= render :partial => 'form', :locals => {:f => f} %>

    <div data-hook="admin_user_new_form_buttons">
      <%= render 'admin/shared/form_actions', record: f.object, cancel: admin_suppliers_invoices_path %>
    </div>
  <% end %>
</div>

app/views/admin/suppliers/invoices/show.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  <%= link_to t(:invoices), admin_suppliers_invoices_path %> /
  <%= @suppliers_invoice.no %>
<% end %>

<div class="row">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title title-padding-lg"> Supplier Invoice #<%= @suppliers_invoice.id %></h4>
    </div>
    <div class="panel-body">
      <table class="table table-condensed table-striped">
        <tbody>
        <tr>
          <td>Supplier Name:</td>
          <td><%= link_to @suppliers_invoice.supplier.name, admin_supplier_path(@suppliers_invoice.supplier) if @suppliers_invoice.supplier.present? %></td>
        </tr>
        <tr>
          <td>Invoice no:</td>
          <td><%= @suppliers_invoice.no %></td>
        </tr>
        <tr>
          <td>Amount:</td>
          <td><%= @suppliers_invoice.amount %></td>
        </tr>
        <tr>
          <td>Invoice date:</td>
          <td><%= @suppliers_invoice.date %></td>
        </tr>
        </tbody>
      </table>
      <% @suppliers_invoice.attachments.each do |attach| %>
        <%= link_to image_tag(attach.picture, width: 200), attach.picture_url, target: "_blank" %>
        <br/><br/>
      <% end %>
    </div>
  </div>
</div>

<% if @suppliers_invoice.is_order %>
  <%= render 'details_of_order_invoice' %>
<% end %>