config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  as :user do
    get "login", to: "users/sessions#new", as: :user_login
    delete "logout", to: "devise/sessions#destroy", as: :user_logout
    get "registration", to: "users/registrations#new", as: :account_registration
  end

  resources :blogs, only: [ :show, :index ] do
    resources :comments, only: [ :create ]
  end

  root to: "home#index"
  get "/sitemap", to: "home#sitemap"
  get "/promo/:q/products", to: "products#index", as: :promotion_products
  post :email_subscription, to: "public#subscribe"
  resources :wishlists, only: [ :index, :destroy ]
  resources :products do
    post :review
    resources :wishlists, only: [ :create ]
    get :quickview
    get :compare
    get :remove_compare
    collection do
    end
  end

  resources :orders, except: [ :index, :new, :create, :destroy ] do
    post :populate, on: :collection
    get :reset, on: :collection
    get :shipped_track
  end

  resources :feedbacks, only: [ :new, :create ]

  get "/c/*id", to: "categories#show", as: :categories
  get "/b/*id", to: "products#brand_show", as: :brands

  resources :carts
  post "/checkout/update_coupon_code", to: "checkout#update_coupon_code"
  get "/checkout", to: "checkout#edit", as: :cart_checkout
  get "/checkout/:state", to: "checkout#edit", as: :checkout_state
  patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout

  post "/paypal", to: "paypal#express", as: :paypal_express
  get "/paypal/confirm", to: "paypal#confirm", as: :confirm_paypal
  get "/paypal/cancel", to: "paypal#cancel", as: :cancel_paypal
  get "/paypal/notify", to: "paypal#notify", as: :notify_paypal

  post "/ssl_commerz", to: "ssl_commerz#ssl_express", as: :ssl_express
  post "/ssl_commerz/confirm", to: "ssl_commerz#confirm", as: :confirm_ssl
  post "/ssl_commerz/cancel", to: "ssl_commerz#cancel", as: :cancel_ssl
  post "/ssl_commerz/failed", to: "ssl_commerz#failed", as: :failed_ssl

  namespace :admin do
    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
        get :login
      end

      collection do
        get :customer
        get :supplier
      end
      resources :store_credits
    end
    resources :print_barcodes do
      collection do
        get :preview
      end
    end
    resources :feedbacks do
      member do
        post :checked_feedback
      end
    end
    resources :contacts do
      member do
        post :checked_query
      end
      collection do
        get :check_order
      end
    end
    get "/subscribers", to: "dashboard#subscribers"
    get "/reports", to: "dashboard#monthly_reports"
    get "/purchase_reports", to: "dashboard#purchase_reports"
    get "/sales_reports", to: "dashboard#sales_reports"
    namespace :suppliers do
      get "/purchase/orders", to: "purchase_orders#index", as: :purchases
      resources :purchase_orders do
        member do
          get :cart
          post :add_item
          get :complete
          post :update_item
          post :update_receive_item
          post :update_purchase
          post :remove_item
          post :remove_receive_item
          get :receive
          post :received_purchase
        end
        collection do
          get :refunds
          get :new_order
          get :refund
          get :new_refund_items
          post :return_item
        end
      end
      post "process_invoice"
      resources :refunds do
        collection do
          get :new_refund
          get :refund
          get :refund_items
          get :edit_refund
          delete :remove_refund_item
          post :new_return_item
          post :update_refund
          delete :remove_refund
        end
      end
      resources :payments do
        get :complete, on: :member
        get :confirm, on: :member
        get :bounce, on: :member
        get :rescheduled, on: :member
        get :download, on: :collection
        get :commission_report, on: :collection
      end
      resources :invoices do
        get "details"
        get "history"
      end
      resources :discounts
      resources :text_messages
    end

    resources :suppliers do
      member do
        get :address
        put :address
        get :orders
        get :get_history
        get :statement
      end
      collection do
        get "purchase_list", to: "suppliers#purchase_list"
        get "supplier_balance", to: "suppliers#supplier_balance"
      end
    end
    resources :prints
    resources :categories
    resources :brands
    resources :gallery_images
    resources :products do
      member do
        get :stock
        get :review
        delete :remove_review
        put :approved
      end
      collection do
        get :inventory
        get :purchase_product_search
        get :reorder_leveled
        get :name_search
      end
      resources :images
      resources :variants
    end
    resources :blogs do
      resources :comments, only: [ :destroy, :edit, :update ]
    end
    resources :home_sliders
    resources :coupons
    resources :shipping_methods

    resources :payment_methods

    resources :stock_locations do
      member do
        get :stock_items
      end
      resources :stock_movements
    end
    resources :stock_items
    resources :stock_transfers
    get :shipment_tracking, to: "orders#shipment_tracking"

    resources :orders, except: [ :show ] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        post :add_product
        post :shipment
        post :update_line_item
        post :remove_line_item
      end
      collection do
        get :new_orders
        get :drafts
      end

      resources :state_changes, only: [ :index ]

      resource :customer, controller: "orders/customers"
      resources :customer_returns, only: [ :index, :new, :edit, :create, :update ] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [ :new, :create, :edit, :update ]
      end

      resources :reimbursements, only: [ :index, :create, :show, :edit, :update ] do
        member do
          post :perform
        end
      end
    end
  end
  get "/admin", to: "admin/dashboard#index", as: :admin
  get "/admin/orders/:id/tracks", to: "admin/orders#track", as: :admin_order_track
  patch "/admin/order/:id/update_state/", to: "admin/orders#update_state", as: :order_state

  resources :contacts, only: [ :new, :create ]
  get "/frequently-asked-question", to: "public#faq", as: :faq
  get "/secure_shopping", to: "public#secure_shopping", as: :secure_shopping
  get "/coupon-code", to: "public#coupon", as: :coupon
  get "/return-policy", to: "public#return_policy", as: :return_policy
  get "/our-promise", to: "public#promise", as: :our_promise
  match "/dedicated-customer-support", to: "public#contact_us", via: [ :get, :post ], as: :contact_us
  get "/free-shipping-worldwide", to: "public#international", as: :international
  get "/safe_shopping_guarantee", to: "public#safe_shopping_guarantee", as: :safe_shopping_guarantee
  get "/about_us", to: "public#about_us", as: :about_us
  get "/privacy_policy", to: "public#privacy_policy", as: :privacy_policy
  get "/term_condition", to: "public#term_condition", as: :term_condition
  get "/my_account", to: "users#my_account"
  get "/cart", to: "public#cart"
  get "/p_checkout", to: "public#checkout"
  post "/email_subscription", to: "public#subscribe"
  post "/checkout", to: "checkout#check_coupon_code"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users
      get "home", to: "home#index"
      get "my_account", to: "users#my_account"
      resources :products, only: [ :index, :show ] do
        get "filters", on: :collection
        get "get_names", on: :collection
      end
      resources :wishlists, only: [ :index, :create ] do
        get :remove
      end
      resources :contacts, only: [ :create ]
      resources :orders, only: [ :index, :update, :show ] do
        post :populate, on: :collection
        post :current_cart, on: :collection
        post :detail, on: :collection
        post :current_state, on: :collection
        post :update_address, on: :collection
        post :update_order, on: :collection
        post :get_ship_address, on: :collection
        post :get_shipments, on: :collection
        post :get_payment_info, on: :collection
      end
      resources :reviews, only: [ :index, :create, :update, :destroy ]
      resources :shipments, only: [ :create, :update ] do
        member do
          put :ship
        end
      end
      resources :line_items do
        post :remove_item, on: :collection
      end

      post "/checkout/update_order/:state", to: "checkout#update_order", as: :update_checkout
    end
  end
end

app/controllers/admin/orders/customers_controller.rb
module Admin
  module Orders
    class CustomersController < BaseController
      respond_to? :html
      before_action :set_order, only:[:show, :update]

      def show

      end

      def update

        p @order
        p "***********************************************"

        if @order.update(order_attributes)
          p @order
          p "***********************************************"
          redirect_to admin_order_customer_path
        else
          p @order
          p "***********************************************"
          p "***********************************************"
          p "***********************************************"
          redirect_to admin_order_customer_path
        end
      end

      private
       def order_attributes
         params.require(:order).permit!
       end

      def set_order
        @order = Order.find_by_number(params[:order_id])
      end
    end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # before_action :check_authorization, except: [:reset, :show]
  # before_action :apply_coupon_code, only: :update
  # rescue_from ActiveRecord::RecordNotFound, :with => :page_not_found
  # helper 'products', 'orders'
  # before_action :set_order

  respond_to :html

  # before_action :assign_order_with_lock, only: :update
  # before_action :verify_authentication, only: [:shipped_track]
  # skip_before_action :verify_authenticity_token, only: [:populate]

  layout 'product'

  def show
    @order = Order.includes(line_items: [product: [:images]]).find_by_number!(params[:id])
  end

  def update
    if @order.contents.update_cart(order_params)
      respond_with(@order) do |format|
        format.html do
          if params.has_key?(:checkout)
            @order.next if @order.cart?
            if @order.state == 'address'
              redirect_to checkout_address_path(state: 'address')
            elsif @order.state == 'payment'
              redirect_to checkout_payment_path(state: 'payment')
            else
              redirect_to checkout_state_path(@order.checkout_steps.first)
            end
          else
            redirect_to cart_checkout_path
          end
        end
      end
    else
      respond_with(@order)
    end
  end

  # Shows the current incomplete order from the session
  def edit
    @order = current_order || Order.incomplete.
        includes(line_items: [variant: [:images, :option_values, :product]]).
        find_or_initialize_by(guest_token: cookies.signed[:guest_token])
    associate_user
    return redirect_to root_path unless @order.line_items.length > 0
    # product = @order.line_items.first.product
    # # @recommend_products = product.recommended_products
    # # unless @recommend_products.length > 0
    # #   @recommend_products = product.get_recom_products
    # # end
    @title = "Your Shipping Bag – Brandcruz.com Secure Shopping"
    @keywords = "brandcruz, Brand Cruz, Brandcruz.com"
    @description = "Shop for shopping cart cover at Brandcruz.com. Free Shipping. Free Returns. All the time."
  end

  def reset
    current_order.empty!
    current_order.destroy
    redirect_to products_path
  end

  # Adds a new item to the order (creating a new order if none already exists)
  def populate
    @error = nil
    order = current_order(true)
    variant = Product.find(params[:variant_id])
    quantity = params[:quantity].to_i
    size = params[:size]
    options = params[:options] || {}

    # 2,147,483,647 is crazy. See issue #2695.
    if quantity.between?(1, 2_147_483_647)
      begin
        line_item = order.contents.add(variant, quantity, options)
        line_item.size = size
        line_item.save
      rescue ActiveRecord::RecordInvalid => e
        @error = e.record.errors.full_messages.join(", ")
      end
    else
      @error = t(:please_enter_reasonable_quantity)
    end

    respond_to do |format|
      format.html do
        if @error
          flash[:error] = @error
          redirect_back_or_default(root_path)
        else
          respond_with(order) do |format|
            format.html { redirect_to cart_checkout_path }
          end
        end
      end
      format.js { render layout: false }
    end
  end

  def shipped_track
    @orders = Order.all #try_spree_current_user.orders.complete.order('completed_at desc')
    @order = Order.find_by_number(params[:order_id]) || Order.find_by_id(params[:order_id])
    @trackes = @order.shipment.trackings.order('created_at desc').group_by { |track| track.created_at.strftime('%A, %d %b') }
  end

  def empty
    if @order = current_order
      @order.empty!
    end

    redirect_to cart_checkout_path
  end

  def accurate_title
    if @order && @order.completed?
      t(:order_number, :number => @order.number)
    else
      t(:shopping_cart)
    end
  end

  def check_authorization
    order = Order.find_by_number(params[:id]) || current_order
    if order
      authorize! :edit, order, cookies[:guest_token]
    else
      authorize! :create, Order
    end
  end

  def apply_coupon
    @order = current_order
    @error = "Order not found"
    if @order.present? && params[:coupon_code].present?
      @order.coupon_code = params[:coupon_code]

      handler = PromotionHandler::Coupon.new(@order).apply

      if handler.error.present?
        @error = handler.error
      elsif handler.success
        @success = handler.success
      end
    else
      @error = "Order or coupon code not found"
    end

    respond_to do |format|
      format.js {}
    end
  end

  def remove_coupon
    @order = current_order
    @success = false
    if @order.present?
      order_promotions = @order.order_promotions.where(promotion_id: params[:id]).first
      adjustments = @order.adjustments
      if adjustments.length > 0
        adjustments.destroy_all
      end
      order_promotions.destroy
      # Adjustable::AdjustmentsUpdater.update(@order)
      @success = true
    end
  end

  private

  def set_order
    @order = current_order(true)
  end

  def apply_coupon_code
    assign_order_with_lock

    if params[:orders] && params[:orders][:coupon_code] && @order.present?

      @order.coupon_code = params[:orders][:coupon_code]

      handler = PromotionHandler::Coupon.new(@order).apply

      if handler.error.present?
        flash[:error] = handler.error
        respond_with(@order) { |format| format.html { redirect_to cart_checkout_path } } and return
      elsif handler.success
        flash[:success] = handler.success
      end
    end
  end

  def order_params
    if params[:orders]
      params[:orders].permit(*permitted_order_attributes)
    else
      {}
    end
  end

  def verify_authentication
    unless current_user
      redirect_to '/secure-user-signin-signup'
    end
  end

  def assign_order_with_lock
    @order = current_order(lock: true)
    unless @order
      flash[:error] = t(:order_not_found)
      redirect_to root_path and return
    end
  end
end

app/views/admin/orders/_add_product.html.erb
<%#= render partial: "admin/variants/autocomplete", formats: :js %>
<%#= render partial: "admin/variants/autocomplete_stock", formats: :js %>

<!--<div class="panel panel-default" id="add-line-item" data-hook>-->
  <!--<div class="panel-heading">-->
    <!--<h1 class="panel-title">-->
      <!--<%#= t(:add_product) %>-->
    <!--</h1>-->
  <!--</div>-->
  <!--<div class="panel-body">-->
    <!--<div data-hook="add_product_name">-->
      <!--<%#= label_tag :add_variant_id, t(:name_or_sku) %>-->
      <!--<%#= hidden_field_tag :add_variant_id, "", class: "variant_autocomplete fullwidth-input" %>-->
    <!--</div>-->

    <!--<div id="stock_details"></div>-->
  <!--</div>-->
<!--</div>-->

app/views/admin/orders/drafts.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to 'New Order', new_admin_order_path, :class => "btn-success", :icon => 'plus', :id => 'admin_new_order' %>
<% end if can? :create, Order %>

<% content_for :page_tabs do %>
  <li role="presentation" ><a  href="<%= new_orders_admin_orders_path %>">New Orders</a></li>
  <li role="presentation" ><a href="<%= admin_orders_path %>">Approved Orders</a></li>
  <li role="presentation" class="active"><a href="#">Canceled Orders</a></li>
<% end %>

<%# content_for :content_top do %>
<%# end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= form_for [:admin, @search], method: 'get' do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => 'Start' %>
                  <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => 'Stop' %>
                  <span class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :number, 'Number' %>
            <%= f.text_field :number, class: 'form-control js-quick-search-target', value: params[:q][:number] %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :state, "Status" %>
            <%= f.select :state, Order::ORDER_STATES.map { |s| [t("order_state.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:state]}, :class => 'select2 jsx-filterable js-filter-select' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, t(:payment_state) %>
            <%= f.select :payment_state, Order::PAYMENT_STATES.map { |s| [t("payment_states.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:payment_state]}, :class => 'select2 jsx-filterable js-filter-select' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :shipment_state, t(:shipment_state) %>
            <%= f.select :shipment_state, Order::SHIPMENT_STATES.map { |s| [t("shipment_states.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:shipment_state]}, :class => 'select2 xjs-filterable js-filter-select' %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :email, 'Email' %>
            <%= f.text_field :email, class: 'form-control js-filterable',  value: params[:q][:state] %>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <%= button 'Filter Results', ' fa fa-search' %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
    <tr data-hook="admin_orders_index_headers">
      <th>
        <%= @show_only_completed ? 'Completed At' : 'Created At' %>
      </th>
      <th> Number</th>
      <th>Status</th>
      <th>Canceled At</th>
      <th>Canceled By</th>
      <th> P.State</th>
      <th> S.State</th>
      <th> Email</th>
      <th> Total</th>
      <th class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr class="state-<%= order.state.downcase if order.state.present? %> <%= cycle('odd', 'even') %>">
        <td title="Year: <%= order.created_at.strftime('%Y') %>">
          <%= (@show_only_completed ? order.completed_at : order.created_at).strftime('%d %b %H:%M %p') %>
        </td>
        <td>
          <%= link_to order.number, edit_admin_order_path(order) %>
        </td>
        <td>
              <span class="label label-<%= order.state.downcase if order.state %>">
                <%= order.state.upcase if order.state %>
              </span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td title="Year: <%= order.created_at.strftime('%Y') %>">
          <%= (@show_only_completed ? order.canceled_at : order.canceled_at).strftime('%d %b %H:%M %p') %>
        </td>
        <td>
          <% if order.canceled_at %>
            <%= link_to order.canceler.name.upcase, admin_user_path(order.canceler) %>
          <% end %>
        </td>
        <td>
          <% if order.payment_state %>
                  <span class="label label-<%= order.payment_state %>">
                    <%= link_to order.payment_state.upcase, admin_order_payments_path(order) %>
                  </span>
          <% end %>
        </td>
        <td>
          <% if order.shipment_state %>
            <span class="label label-<%= order.shipment_state.downcase if order.shipment_state %>"><%= t("shipment_states.#{order.shipment_state.upcase}") %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
          <% end %>
        </td>

        <td>
          <% if order.user %>
            <%= link_to order.user.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
        </td>
        <td>
          <%= amount_with_currency(order.total) %>
        </td>
        <td class='actions actions-1'>
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    No Order Canceled Yet
  </div>
<% end %>

<%= render 'admin/shared/index_table_options', collection: @orders, simple: true %>

<%= paginate @orders, theme: 'twitter-bootstrap-4' %>

app/views/admin/orders/new_orders.html.erb
<% content_for :page_title do %>
  <%= plural_resource_name(Order) %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to 'New Order', new_admin_order_path, :class => "btn-success", :icon => 'plus', :id => 'admin_new_order' %>
<% end if can? :create, Order %>

<% content_for :page_tabs do %>
  <li role="presentation" class="active"><a  href="#">New Orders</a></li>
  <li role="presentation" ><a  href="<%= admin_orders_path %>">Approved Orders</a></li>
  <li role="presentation"><a href="<%= drafts_admin_orders_path %>">Canceled Orders</a></li>
<% end %>

<%# content_for :content_top do %>
<%# end %>

<% content_for :table_filter do %>
  <div data-hook="admin_orders_index_search">

    <%= form_for [:admin, @search], method: 'get' do |f| %>
      <div class="row">
        <div class="date-range-filter col-md-8">
          <div class="form-group">
            <%= label_tag :q_created_at_gt, t(:date_range) %>
            <div class="row no-padding-bottom">
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_gt, :class => 'datepicker datepicker-from form-control', :value => params[:q][:created_at_gt], :placeholder => 'Start' %>
                  <span class="input-group-addon">
                        <i class="fa fa-calendar"></i>
                      </span>
                </div>

              </div>
              <div class="col-md-6">
                <div class="input-group">
                  <%= f.text_field :created_at_lt, :class => 'datepicker datepicker-to form-control', :value => params[:q][:created_at_lt], :placeholder => 'Stop' %>
                  <span class="input-group-addon">
                    <i class="fa fa-calendar"></i>
                  </span>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :number, 'Number' %>
            <%= f.text_field :number, class: 'form-control js-quick-search-target', value: params[:q][:number] %>
          </div>
        </div>

      </div>

      <div class="row">

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :state, "Status" %>
            <%= f.select :state, Order::ORDER_STATES.map { |s| [t("order_state.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:state]}, :class => 'select2 jsx-filterable js-filter-select' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :q_payment_state_eq, t(:payment_state) %>
            <%= f.select :payment_state, Order::PAYMENT_STATES.map { |s| [t("payment_states.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:payment_state]}, :class => 'select2 jsx-filterable js-filter-select' %>
          </div>
        </div>

        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :shipment_state, t(:shipment_state) %>
            <%= f.select :shipment_state, Order::SHIPMENT_STATES.map { |s| [t("shipment_states.#{s}"), s] }, {:include_blank => true,:selected => params[:q][:shipment_state]}, :class => 'select2 xjs-filterable js-filter-select' %>
          </div>
        </div>

      </div>

      <div class="row">
        <div class="col-md-4">
          <div class="form-group">
            <%= label_tag :email, 'Email' %>
            <%= f.text_field :email, class: 'form-control js-filterable',  value: params[:q][:state] %>
          </div>
        </div>
      </div>

      <div class="form-actions">
        <%= button 'Filter Results', ' fa fa-search' %>
      </div>
    <% end %>
  </div>
<% end %>

<% if @orders.any? %>
  <table class="table" id="listing_orders" data-hook>
    <thead>
    <tr data-hook="admin_orders_index_headers">
      <th>
        <%= @show_only_completed ? 'Completed At' : 'Created At' %>
      </th>
      <th> Number</th>
      <th>Status</th>
      <th> P.State</th>
      <th> S.State</th>
      <th> Email</th>
      <th> Total</th>
      <th class="actions"></th>
    </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
      <tr class="state-<%= order.state.downcase if order.state.present? %> <%= cycle('odd', 'even') %>">
        <td title="Year: <%= order.created_at.strftime('%Y') %>">
          <%= (@show_only_completed ? order.completed_at : order.created_at).strftime('%d %b %H:%M %p') %>
        </td>
        <td>
          <%= link_to order.number, edit_admin_order_path(order) %>
        </td>
        <td>
              <span class="label label-<%= order.state.downcase if order.state %>">
                <%= order.state.upcase if order.state %>
              </span>
          <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_state_eq" data-ransack-value="<%= order.state %>"></span>
        </td>
        <td>
          <% if order.payment_state %>
                  <span class="label label-<%= order.payment_state %>">
                    <%= link_to order.payment_state.upcase, admin_order_payments_path(order) %>
                  </span>
          <% end %>
        </td>
        <td>
          <% if order.shipment_state %>
            <span class="label label-<%= order.shipment_state %>"><%= t("shipment_states.#{order.shipment_state.upcase}") %></span>
            <span class="icon icon-filter filterable js-add-filter" data-ransack-field="q_shipment_state_eq" data-ransack-value="<%= order.shipment_state %>"></span>
          <% end %>
        </td>

        <td>
          <% if order.user %>
            <%= link_to order.user.email, edit_admin_user_path(order.user) %>
          <% else %>
            <%= mail_to order.email %>
          <% end %>
        </td>
        <td>
          <%= amount_with_currency(order.total) %>
        </td>
        <td class='actions actions-1'>
          <%= link_to_edit_url edit_admin_order_path(order), :title => "admin_edit_#{dom_id(order)}", :no_text => true %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    No Resource Found,
    <%= link_to('Add One', new_admin_order_url) if can? :create, Order %>!
  </div>
<% end %>

<%= render 'admin/shared/index_table_options', collection: @orders, simple: true %>

<%= paginate @orders, theme: 'twitter-bootstrap-4' %>