config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  as :user do
    get "login", to: "users/sessions#new", as: :user_login
    delete "logout", to: "devise/sessions#destroy", as: :user_logout
    get "registration", to: "users/registrations#new", as: :account_registration
  end

  resources :blogs, only: [ :show, :index ] do
    resources :comments, only: [ :create ]
  end

  root to: "home#index"
  get "/sitemap", to: "home#sitemap"
  get "/promo/:q/products", to: "products#index", as: :promotion_products
  post :email_subscription, to: "public#subscribe"
  resources :wishlists, only: [ :index, :destroy ]
  resources :products do
    post :review
    resources :wishlists, only: [ :create ]
    get :quickview
    get :compare
    get :remove_compare
    collection do
    end
  end

  resources :orders, except: [ :index, :new, :create, :destroy ] do
    post :populate, on: :collection
    get :reset, on: :collection
    get :shipped_track
  end

  resources :feedbacks, only: [ :new, :create ]

  get "/c/*id", to: "categories#show", as: :categories
  get "/b/*id", to: "products#brand_show", as: :brands

  resources :carts
  post "/checkout/update_coupon_code", to: "checkout#update_coupon_code"
  get "/checkout", to: "checkout#edit", as: :cart_checkout
  get "/checkout/:state", to: "checkout#edit", as: :checkout_state
  patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout

  post "/paypal", to: "paypal#express", as: :paypal_express
  get "/paypal/confirm", to: "paypal#confirm", as: :confirm_paypal
  get "/paypal/cancel", to: "paypal#cancel", as: :cancel_paypal
  get "/paypal/notify", to: "paypal#notify", as: :notify_paypal

  post "/ssl_commerz", to: "ssl_commerz#ssl_express", as: :ssl_express
  post "/ssl_commerz/confirm", to: "ssl_commerz#confirm", as: :confirm_ssl
  post "/ssl_commerz/cancel", to: "ssl_commerz#cancel", as: :cancel_ssl
  post "/ssl_commerz/failed", to: "ssl_commerz#failed", as: :failed_ssl

  namespace :admin do
    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
        get :login
      end

      collection do
        get :customer
        get :supplier
      end
      resources :store_credits
    end
    resources :print_barcodes do
      collection do
        get :preview
      end
    end
    resources :feedbacks do
      member do
        post :checked_feedback
      end
    end
    resources :contacts do
      member do
        post :checked_query
      end
      collection do
        get :check_order
      end
    end
    get "/subscribers", to: "dashboard#subscribers"
    get "/reports", to: "dashboard#monthly_reports"
    get "/purchase_reports", to: "dashboard#purchase_reports"
    get "/sales_reports", to: "dashboard#sales_reports"
    namespace :suppliers do
      get "/purchase/orders", to: "purchase_orders#index", as: :purchases
      resources :purchase_orders do
        member do
          get :cart
          post :add_item
          get :complete
          post :update_item
          post :update_receive_item
          post :update_purchase
          post :remove_item
          post :remove_receive_item
          get :receive
          post :received_purchase
        end
        collection do
          get :refunds
          get :new_order
          get :refund
          get :new_refund_items
          post :return_item
        end
      end
      post "process_invoice"
      resources :refunds do
        collection do
          get :new_refund
          get :refund
          get :refund_items
          get :edit_refund
          delete :remove_refund_item
          post :new_return_item
          post :update_refund
          delete :remove_refund
        end
      end
      resources :payments do
        get :complete, on: :member
        get :confirm, on: :member
        get :bounce, on: :member
        get :rescheduled, on: :member
        get :download, on: :collection
        get :commission_report, on: :collection
      end
      resources :invoices do
        get "details"
        get "history"
      end
      resources :discounts
      resources :text_messages
    end

    resources :suppliers do
      member do
        get :address
        put :address
        get :orders
        get :get_history
        get :statement
      end
      collection do
        get "purchase_list", to: "suppliers#purchase_list"
        get "supplier_balance", to: "suppliers#supplier_balance"
      end
    end
    resources :prints
    resources :categories
    resources :brands
    resources :gallery_images
    resources :products do
      member do
        get :stock
        get :review
        delete :remove_review
        put :approved
      end
      collection do
        get :inventory
        get :purchase_product_search
        get :reorder_leveled
        get :name_search
      end
      resources :images
      resources :variants
    end
    resources :blogs do
      resources :comments, only: [ :destroy, :edit, :update ]
    end
    resources :home_sliders
    resources :coupons
    resources :shipping_methods

    resources :payment_methods

    resources :stock_locations do
      member do
        get :stock_items
      end
      resources :stock_movements
    end
    resources :stock_items
    resources :stock_transfers
    get :shipment_tracking, to: "orders#shipment_tracking"

    resources :orders, except: [ :show ] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        post :add_product
        post :shipment
        post :update_line_item
        post :remove_line_item
      end
      collection do
        get :new_orders
        get :drafts
      end

      resources :state_changes, only: [ :index ]

      resource :customer, controller: "orders/customers"
      resources :customer_returns, only: [ :index, :new, :edit, :create, :update ] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [ :new, :create, :edit, :update ]
      end

      resources :reimbursements, only: [ :index, :create, :show, :edit, :update ] do
        member do
          post :perform
        end
      end
    end
  end
  get "/admin", to: "admin/dashboard#index", as: :admin
  get "/admin/orders/:id/tracks", to: "admin/orders#track", as: :admin_order_track
  patch "/admin/order/:id/update_state/", to: "admin/orders#update_state", as: :order_state

  resources :contacts, only: [ :new, :create ]
  get "/frequently-asked-question", to: "public#faq", as: :faq
  get "/secure_shopping", to: "public#secure_shopping", as: :secure_shopping
  get "/coupon-code", to: "public#coupon", as: :coupon
  get "/return-policy", to: "public#return_policy", as: :return_policy
  get "/our-promise", to: "public#promise", as: :our_promise
  match "/dedicated-customer-support", to: "public#contact_us", via: [ :get, :post ], as: :contact_us
  get "/free-shipping-worldwide", to: "public#international", as: :international
  get "/safe_shopping_guarantee", to: "public#safe_shopping_guarantee", as: :safe_shopping_guarantee
  get "/about_us", to: "public#about_us", as: :about_us
  get "/privacy_policy", to: "public#privacy_policy", as: :privacy_policy
  get "/term_condition", to: "public#term_condition", as: :term_condition
  get "/my_account", to: "users#my_account"
  get "/cart", to: "public#cart"
  get "/p_checkout", to: "public#checkout"
  post "/email_subscription", to: "public#subscribe"
  post "/checkout", to: "checkout#check_coupon_code"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users
      get "home", to: "home#index"
      get "my_account", to: "users#my_account"
      resources :products, only: [ :index, :show ] do
        get "filters", on: :collection
        get "get_names", on: :collection
      end
      resources :wishlists, only: [ :index, :create ] do
        get :remove
      end
      resources :contacts, only: [ :create ]
      resources :orders, only: [ :index, :update, :show ] do
        post :populate, on: :collection
        post :current_cart, on: :collection
        post :detail, on: :collection
        post :current_state, on: :collection
        post :update_address, on: :collection
        post :update_order, on: :collection
        post :get_ship_address, on: :collection
        post :get_shipments, on: :collection
        post :get_payment_info, on: :collection
      end
      resources :reviews, only: [ :index, :create, :update, :destroy ]
      resources :shipments, only: [ :create, :update ] do
        member do
          put :ship
        end
      end
      resources :line_items do
        post :remove_item, on: :collection
      end

      post "/checkout/update_order/:state", to: "checkout#update_order", as: :update_checkout
    end
  end
end

app/models/admin/suppliers.rb
module Admin::Suppliers
  def self.table_name_prefix
    'admin_suppliers_'
  end
end

app/models/admin/suppliers/invoices.rb
module Admin::Suppliers::Invoices
  def self.table_name_prefix
    'admin_suppliers_invoices_'
  end
end

app/controllers/admin/refunds_controller.rb
module Admin
  class RefundsController < BaseController
    before_action :load_order


    # rescue_from Core::GatewayError, with: :spree_core_gateway_error, only: :create TODO: Need to active

    def new
      @payment = Payment.friendly.find(params[:payment_id])
      @refund = @payment.refunds.new
      @order = Order.friendly.find(params[:order_id])
    end

    def edit
      @payment = Payment.friendly.find(params[:payment_id])
      @refund = @payment.refunds.find_by_id(params[:id])
      @order = Order.friendly.find(params[:order_id])
    end

    def create
      @payment = Payment.friendly.find(params[:payment_id])
      @order = Order.friendly.find(params[:order_id])
      @refund = @payment.refunds.new(refund_params)
      respond_to do |format|
        format.html do
          if @refund.save
            flash[:success] = "Order Item Successfully returned"
            redirect_to edit_admin_payment_method_path(@payment)
          else
            render :new
          end
        end
      end
    end

    private

    def location_after_save
      admin_order_payments_path(@payment.order)
    end

    def load_order
      # the spree/admin/shared/order_tabs partial expects the @order instance variable to be set
      @order = @payment.order if @payment
    end

    def refund_reasons
      @refund_reasons ||= RefundReason.active.all
    end

    def build_resource
      super.tap do |refund|
        refund.amount = refund.payment.credit_allowed
      end
    end

    def spree_core_gateway_error(error)
      flash[:error] = error.message
      render :new
    end

    def refund_params
      params.require(:refund).permit!
    end
  end
end

app/controllers/admin/suppliers/discounts_controller.rb
module Admin
  module Suppliers
    class DiscountsController < BaseController
      before_action :set_admin_suppliers_discount, only: [:show, :edit, :destroy]

      # GET /admin/suppliers/discounts
      # GET /admin/suppliers/discounts.json
      def index
        @discounts = Admin::Suppliers::Discount.all.order(created_at: :desc)
        @discounts = @discounts.page(params[:page]).per(20)
      end

      # GET /admin/suppliers/discounts/1
      # GET /admin/suppliers/discounts/1.json
      def show
      end

      # GET /admin/suppliers/discounts/new
      def new
        @invoices = Admin::Suppliers::Invoice.invoices
        @invoice = @invoices.find_by_id(params[:invoice_id]) if params[:invoice_id]
        p @invoice
        @discount = Admin::Suppliers::Discount.new(invoice_id: @invoice.id) if @invoice
      end

      # GET /admin/suppliers/discounts/1/edit
      def edit
      end

      # POST /admin/suppliers/discounts
      # POST /admin/suppliers/discounts.json
      def create

        @invoice = Admin::Suppliers::Invoice.find_by_id(discount_params[:invoice_id])
        @discount = @invoice.discounts.build(discount_params.merge(supplier_id: @invoice.supplier_id))
        if @discount.save
          if @invoice.due_amount <= 0
            @invoice.is_complete = true
          else
            @invoice.is_complete = false
          end
          @invoice.save
          redirect_to admin_suppliers_discounts_path
        else
          @discount.errors
          render :new, invoice_id: @invoice.id
        end
      end

      # PATCH/PUT /admin/suppliers/discounts/1
      # PATCH/PUT /admin/suppliers/discounts/1.json
      def update
        @invoice = Admin::Suppliers::Invoice.find_by_id(discount_params[:invoice_id])
        @discount = @invoice.discounts.find_by_id(params[:id])
        @discount.update(discount_params.merge(supplier_id: @invoice.supplier_id))
        if @discount.save
          redirect_to admin_suppliers_discounts_path
        end
      end

      # DELETE /admin/suppliers/discounts/1
      # DELETE /admin/suppliers/discounts/1.json
      def destroy
        @discount.destroy
        respond_to do |format|
          format.html { redirect_to admin_suppliers_discounts_url, notice: 'Discount was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_suppliers_discount
        @discount = Admin::Suppliers::Discount.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def discount_params
        params.require(:admin_suppliers_discount).permit(:amount, :date, :discount_by, :discount_reason, :invoice_no, :invoice_id, :supplier_id)
      end
    end
  end
end

app/controllers/admin/suppliers/invoices_controller.rb
module Admin
  module Suppliers
    class InvoicesController < BaseController
        before_action :set_admin_suppliers_invoice, only: [:show, :edit, :update, :destroy]

      # GET /admin/suppliers/invoices
      # GET /admin/suppliers/invoices.json
      def index
        @suppliers_invoices = Admin::Suppliers::Invoice.all.order(created_at: :desc)
        @suppliers_invoices = @suppliers_invoices.page(params[:page]).per(20)
      end

      # GET /admin/suppliers/invoices/1
      # GET /admin/suppliers/invoices/1.json
      def show
      end

      # GET /admin/suppliers/invoices/new
      def new
        @suppliers_invoice = Admin::Suppliers::Invoice.new
        @suppliers_invoice.attachments.build
      end

      # GET /admin/suppliers/invoices/1/edit
      def edit
      end

      # POST /admin/suppliers/invoices
      # POST /admin/suppliers/invoices.json
      def create
        @suppliers_invoice = Admin::Suppliers::Invoice.new(admin_suppliers_invoice_params)

        respond_to do |format|
          if @suppliers_invoice.save
            format.html { redirect_to @suppliers_invoice, notice: 'Invoice was successfully created.' }
            format.json { render :show, status: :created, location: @suppliers_invoice }
          else
            format.html { render :new }
            format.json { render json: @suppliers_invoice.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /admin/suppliers/invoices/1
      # PATCH/PUT /admin/suppliers/invoices/1.json
      def update
        respond_to do |format|
          if @suppliers_invoice.update(admin_suppliers_invoice_params)
            format.html { redirect_to @suppliers_invoice, notice: 'Invoice was successfully updated.' }
            format.json { render :show, status: :ok, location: @suppliers_invoice }
          else
            format.html { render :edit }
            format.json { render json: @suppliers_invoice.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /admin/suppliers/invoices/1
      # DELETE /admin/suppliers/invoices/1.json
      def destroy
        @suppliers_invoice.destroy
        respond_to do |format|
          format.html { redirect_to admin_suppliers_invoices_url, notice: 'Invoice was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      def history
        @invoice = Admin::Suppliers::Invoice.find_by_id(params[:invoice_id])
      end

      def details
        @invoice = Admin::Suppliers::Invoice.find_by_id(params[:invoice_id])
        render layout: false
      end
      private
      # Use callbacks to share common setup or constraints between actions.
      def set_admin_suppliers_invoice
        @suppliers_invoice = Admin::Suppliers::Invoice.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def admin_suppliers_invoice_params
        params.require(:admin_suppliers_invoice).permit(:supplier_id, :no, :amount, :date, :transport_cost, attachments_attributes: [:id, :picture, :_destroy])
      end
    end
  end
end

app/helpers/admin/suppliers/discounts_helper.rb
module Admin::Suppliers::DiscountsHelper
end

app/views/admin/suppliers/refunds/edit.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  <%= link_to t(:refunds), admin_suppliers_refunds_path %> /
  <%= "Editing Refund" %>
<% end %>

<% content_for :page_actions do %>
  <%= render "admin/shared/supplier_links"  %>
<% end %>

<div class="panel-body">
  <div data-hook="admin_user_edit_form_header">
    <%= render :partial => 'admin/shared/error_messages', :locals => {:target => @refund} %>
  </div>

  <div data-hook="admin_user_edit_form">
    <%= form_for [:admin, @refund], url: admin_suppliers_refund_url, method: :put do |f| %>
      <%= render :partial => 'form', :locals => {:f => f} %>

      <div data-hook="admin_user_new_form_buttons">
        <%= render 'admin/shared/form_actions', record: f.object, cancel: admin_suppliers_refunds_path %>
      </div>
    <% end %>
  </div>
</div>

app/views/admin/suppliers/refunds/edit_refund.html.erb
<% content_for :page_title do %>
  <%= link_to 'Purchase Refunds', refunds_admin_suppliers_purchase_orders_path %> /
  <%= format_datetime_short(@refund.created_at) %> / Editing
<% end %>


<%= form_tag update_refund_admin_suppliers_refunds_path, method: :post do %>
  <div class="row">
    <div class="col-sm-6">
      <div class="panel panel-default jobs-board product-barcodes reset-border-radius">
        <div class="panel-heading">
          <div class="row">
            <div class="col-sm-6">
              <h4 class="panel-title title-padding-lg"><b>Supplier:</b></h4>
            </div>
          </div>
        </div>
        <%= render 'admin/suppliers/supplier_info', supplier: @supplier %>
      </div>
    </div>

    <div class="col-sm-6">
      <div class="panel panel-default jobs-board product-barcodes reset-border-radius">
        <div class="panel-body">
          <table class="table borderless" style="margin-bottom: 0;">
            <tbody>
            <tr>
              <td>
                <b> Refund Date: </b>
              </td>
              <td>
                <%= date_field_tag :date, Date.today, class: "form-control"%>
              </td>
            </tr>
            <tr>
              <td>
                <b> Refund Reason: </b>
              </td>
              <td>
                <%= text_field_tag :refund_reason, '', class: "form-control" %>
              </td>
            </tr>
            </tbody>
          </table>
          <%= hidden_field_tag :id, @refund.id %>

          <%= submit_tag 'Update', class: 'btn btn-info pull-right' %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default jobs-board product-barcodes">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <h4 class="panel-title title-padding-lg">Invoice Items</h4>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <% if @purchases.present? %>
            <table class="table">
              <thead>
              <tr>
                <th>Image</th>
                <th>Code</th>
                <th>Name</th>
                <th>Stock</th>
                <th>Price</th>
                <th>Ordered Qty</th>
                <th>Received Qty</th>
                <th>Returned Qty.</th>
                <th colspan="2"></th>
              </tr>
              </thead>
              <tbody id="purchase-order-products-tbody">

              <% @purchases.each do |purchase| %>
                <tr>
                  <th><%=  link_to "Items of Invoice #{purchase.no}", admin_suppliers_invoice_path(purchase)  %></th>
                </tr>
                <% purchase.items.each do |item| %>
                  <%= render 'refund_item_row', item: item %>
                <% end %>
              <% end %>

              </tbody>
            </table>
          <% else %>
            <div class="alert alert-info no-objects-found">
              <%= t(:no_resource_found, resource: 'Purchase Order') %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <div class="panel panel-default jobs-board product-barcodes">
        <div class="panel-heading">
          <div class="row">
            <div class="col-md-12">
              <h4 class="panel-title title-padding-lg">Refund Items</h4>
            </div>
          </div>
        </div>
        <div class="panel-body">
          <% if @refund.present? %>
            <% if @refund.items.present? %>
              <div>
                <label>Refund Reason: </label>
                <span class="refund-reason"><%= @refund.refund_reason if @refund.present? %></span>
              </div>
              <table class="table">
                <thead>
                <tr>
                  <th>Image</th>
                  <th>Code</th>
                  <th>Name</th>
                  <th>Quantity</th>
                  <th>Total Amount</th>
                  <th>Returned At</th>
                  <th></th>
                </tr>
                </thead>
                <tbody id="purchase-order-return-tbody">
                <% @refund.items.each do |item| %>
                  <%= render 'refunded_items', item: item %>
                <% end %>
                </tbody>
              </table>
            <% else %>
              <div class="alert alert-info no-objects-found">
                <%= t(:no_resource_found, resource: 'Refund Items') %>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>

    </div>
  </div>
<% end %>
<%= render 'admin/shared/modal' %>

app/views/admin/suppliers/refunds/index.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  Refunds
<% end %>
<% content_for :page_actions do %>
  <%= render "admin/shared/supplier_links"  %>
<% end %>

<table class="table">
  <thead>
  <tr>
    <th>Supplier</th>
    <th>Invoice no</th>
    <th>Amount</th>
    <th>Refund by</th>
    <th>Refund Reason</th>
    <th>Date</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <% @refunds.each do |refund| %>
    <tr>
      <td><%= refund.supplier.name %></td>
      <td><%= refund.invoice.no if refund.invoice.present? %></td>
      <td><%= refund.amount %></td>
      <td><%= refund.refund_by %></td>
      <td><%= refund.refund_reason %></td>
      <td><%= I18n.localize(refund.date, format: :long) %></td>
      <td><%= link_to 'Show', refund %></td>
      <td>
        <% unless (refund.is_order && refund.invoice.present?) %>
          <%= link_to 'Edit', refund.is_order ? edit_refund_admin_suppliers_refunds_path(id: refund.id) : edit_admin_suppliers_refund_path(refund) if can? :edit, refund %>
        <% end %>
      </td>
      <td><%= link_to 'Destroy', refund,  method: :delete, data: { confirm: 'Are you sure?' }  %></td>
    </tr>
  <% end %>
  <tbody>

  </tbody>
</table>
<%= paginate @refunds, theme: 'twitter-bootstrap-4' %>

app/views/admin/suppliers/refunds/new.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  <%= link_to t(:refunds), admin_suppliers_refunds_path %> /
  <%= "New Suppliers Refund" %>
<% end %>

<% content_for :page_actions do %>
  <%= render "admin/shared/supplier_links"  %>
<% end %>
<% if @invoice.present? %>
  <div data-hook="admin_user_new_form_header">
    <%= render :partial => 'admin/shared/error_messages', :locals => {:target => @refund} %>
  </div>

  <div data-hook="admin_user_new_form">
    <%= form_for [:admin, @refund], url: admin_suppliers_refunds_url, method: :post do |f| %>
      <%= render :partial => 'form', :locals => {:f => f} %>

      <div data-hook="admin_user_new_form_buttons">
        <%= render 'admin/shared/form_actions', record: f.object, cancel: admin_suppliers_refunds_path %>
      </div>
    <% end %>
  </div>
<% else %>
  <div class="row">
    <div class="col-sm-4">
      <h4 style="margin: 0;"><b>Select Invoice</b></h4>
    </div>

    <div class="col-sm-4">
      <div class="form-group">
        <%= select_tag :invoice_id, options_for_select(@invoices.collect { |inv| ["#{inv.supplier.name}(#{inv.no}/#{inv.amount})", inv.id] }, (@invoice ? @invoice.id : '') ), prompt: 'Select Supplier...', class: 'chosen form-control' %>
      </div>
    </div>
  </div>
  <%= render 'admin/shared/no_data_found', message: '<strong> Info: </strong> Select supplier invoice first for refund!' %>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
        $('#invoice_id').select2();
        $('#invoice_id').change(function () {
            window.location.href = '<%= new_admin_suppliers_refund_path %>?invoice_id=' + $(this).val();
        });
    });
</script>

app/views/admin/suppliers/refunds/new_refund.html.erb
<% content_for :page_title do %>
  <%= link_to 'Purchase Refunds', refunds_admin_suppliers_purchase_orders_path %> / New Refund
<% end %>

<% content_for :page_actions do %>
  <%= link_to 'Cancel', remove_refund_admin_suppliers_refunds_path(id: @refund.id), method: :delete, class: 'btn btn-danger' if @refund %>
<% end %>

<% if @supplier.present? %>

<% else %>
  <div class="row">
    <div class="col-sm-2">
      <h4 style="margin: 0;"><b>Select Supplier</b></h4>
    </div>

    <div class="col-sm-4">
      <div class="form-group">
        <%= select_tag :supplier_id, options_for_select(@suppliers.collect {|sp| [sp.name, sp.id]}, (@supplier ? @supplier.id : '')), prompt: 'Select Supplier...', class: 'chosen form-control' %>
      </div>
    </div>
  </div>

  <%= render 'admin/shared/no_data_found', message: "<strong> Info: </strong> Select supplier first to add purchase item!" %>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
        $('#supplier_id').select2();
        $('#supplier_id').change(function () {
            window.location.href = '<%= new_refund_admin_suppliers_refunds_path %>?supplier_id=' + $(this).val();
        });
    })

</script>

app/views/admin/suppliers/refunds/show.html.erb
<% content_for :page_title do %>
  <%= render partial: 'admin/shared/suppliers_module', locals: {current: :account} %>
<% end %>
<% content_for :page_title do %>
  <%= link_to t(:suppliers), admin_suppliers_path %> /
  <%= link_to t(:refunds), admin_suppliers_refunds_path %> /
  <%= "Refunds to #{@refund.supplier.name}" %>
<% end %>
<div class="row">
  <div class="col-sm-12">
    <p>
      <strong>Supplier:</strong>
      <%= @refund.supplier.name %>
    </p>

    <p>
      <strong>Invoice no:</strong>
      <%= @refund.invoice_no %>
    </p>

    <p>
      <strong>Refund by:</strong>
      <%= @refund.refund_by %>
    </p>

    <p>
      <strong>Refund Reason:</strong>
      <%= @refund.refund_reason %>
    </p>

    <p>
      <strong>Amount:</strong>
      <%= @refund.amount %>
    </p>

    <p>
      <strong>Date:</strong>
      <%= @refund.date %>
    </p>
    <br/>
    <% if @refund.is_order %>
      <%= render 'refund_item' %>
    <% end %>
    <div class="row">
      <div class="col-sm-12">
        <%= link_to 'Back', admin_suppliers_refunds_path, class: 'btn btn-success' %>
        <%= link_to 'Edit', @refund.is_order ? edit_refund_admin_suppliers_refunds_path(id: @refund.id) : edit_admin_suppliers_refund_path(@refund), class: 'btn btn-success'  if can? :edit, @refund %>

      </div>
    </div>
  </div>
</div>