config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => "/ckeditor"
  devise_for :users, controllers: {
      sessions: "users/sessions",
      registrations: "users/registrations",
      passwords: "users/passwords"
  }
  as :user do
    get "login", to: "users/sessions#new", as: :user_login
    delete "logout", to: "devise/sessions#destroy", as: :user_logout
    get "registration", to: "users/registrations#new", as: :account_registration
  end

  resources :blogs, only: [ :show, :index ] do
    resources :comments, only: [ :create ]
  end

  root to: "home#index"
  get "/sitemap", to: "home#sitemap"
  get "/promo/:q/products", to: "products#index", as: :promotion_products
  post :email_subscription, to: "public#subscribe"
  resources :wishlists, only: [ :index, :destroy ]
  resources :products do
    post :review
    resources :wishlists, only: [ :create ]
    get :quickview
    get :compare
    get :remove_compare
    collection do
    end
  end

  resources :orders, except: [ :index, :new, :create, :destroy ] do
    post :populate, on: :collection
    get :reset, on: :collection
    get :shipped_track
  end

  resources :feedbacks, only: [ :new, :create ]

  get "/c/*id", to: "categories#show", as: :categories
  get "/b/*id", to: "products#brand_show", as: :brands

  resources :carts
  post "/checkout/update_coupon_code", to: "checkout#update_coupon_code"
  get "/checkout", to: "checkout#edit", as: :cart_checkout
  get "/checkout/:state", to: "checkout#edit", as: :checkout_state
  patch "/checkout/update/:state", to: "checkout#update", as: :update_checkout

  post "/paypal", to: "paypal#express", as: :paypal_express
  get "/paypal/confirm", to: "paypal#confirm", as: :confirm_paypal
  get "/paypal/cancel", to: "paypal#cancel", as: :cancel_paypal
  get "/paypal/notify", to: "paypal#notify", as: :notify_paypal

  post "/ssl_commerz", to: "ssl_commerz#ssl_express", as: :ssl_express
  post "/ssl_commerz/confirm", to: "ssl_commerz#confirm", as: :confirm_ssl
  post "/ssl_commerz/cancel", to: "ssl_commerz#cancel", as: :cancel_ssl
  post "/ssl_commerz/failed", to: "ssl_commerz#failed", as: :failed_ssl

  namespace :admin do
    resources :users do
      member do
        get :addresses
        put :addresses
        put :clear_api_key
        put :generate_api_key
        get :items
        get :orders
        get :login
      end

      collection do
        get :customer
        get :supplier
      end
      resources :store_credits
    end
    resources :print_barcodes do
      collection do
        get :preview
      end
    end
    resources :feedbacks do
      member do
        post :checked_feedback
      end
    end
    resources :contacts do
      member do
        post :checked_query
      end
      collection do
        get :check_order
      end
    end
    get "/subscribers", to: "dashboard#subscribers"
    get "/reports", to: "dashboard#monthly_reports"
    get "/purchase_reports", to: "dashboard#purchase_reports"
    get "/sales_reports", to: "dashboard#sales_reports"
    namespace :suppliers do
      get "/purchase/orders", to: "purchase_orders#index", as: :purchases
      resources :purchase_orders do
        member do
          get :cart
          post :add_item
          get :complete
          post :update_item
          post :update_receive_item
          post :update_purchase
          post :remove_item
          post :remove_receive_item
          get :receive
          post :received_purchase
        end
        collection do
          get :refunds
          get :new_order
          get :refund
          get :new_refund_items
          post :return_item
        end
      end
      post "process_invoice"
      resources :refunds do
        collection do
          get :new_refund
          get :refund
          get :refund_items
          get :edit_refund
          delete :remove_refund_item
          post :new_return_item
          post :update_refund
          delete :remove_refund
        end
      end
      resources :payments do
        get :complete, on: :member
        get :confirm, on: :member
        get :bounce, on: :member
        get :rescheduled, on: :member
        get :download, on: :collection
        get :commission_report, on: :collection
      end
      resources :invoices do
        get "details"
        get "history"
      end
      resources :discounts
      resources :text_messages
    end

    resources :suppliers do
      member do
        get :address
        put :address
        get :orders
        get :get_history
        get :statement
      end
      collection do
        get "purchase_list", to: "suppliers#purchase_list"
        get "supplier_balance", to: "suppliers#supplier_balance"
      end
    end
    resources :prints
    resources :categories
    resources :brands
    resources :gallery_images
    resources :products do
      member do
        get :stock
        get :review
        delete :remove_review
        put :approved
      end
      collection do
        get :inventory
        get :purchase_product_search
        get :reorder_leveled
        get :name_search
      end
      resources :images
      resources :variants
    end
    resources :blogs do
      resources :comments, only: [ :destroy, :edit, :update ]
    end
    resources :home_sliders
    resources :coupons
    resources :shipping_methods

    resources :payment_methods

    resources :stock_locations do
      member do
        get :stock_items
      end
      resources :stock_movements
    end
    resources :stock_items
    resources :stock_transfers
    get :shipment_tracking, to: "orders#shipment_tracking"

    resources :orders, except: [ :show ] do
      member do
        get :cart
        post :resend
        get :open_adjustments
        get :close_adjustments
        put :approve
        put :cancel
        put :resume
        post :add_product
        post :shipment
        post :update_line_item
        post :remove_line_item
      end
      collection do
        get :new_orders
        get :drafts
      end

      resources :state_changes, only: [ :index ]

      resource :customer, controller: "orders/customers"
      resources :customer_returns, only: [ :index, :new, :edit, :create, :update ] do
        member do
          put :refund
        end
      end

      resources :adjustments
      resources :return_authorizations do
        member do
          put :fire
        end
      end
      resources :payments do
        member do
          put :fire
        end

        resources :log_entries
        resources :refunds, only: [ :new, :create, :edit, :update ]
      end

      resources :reimbursements, only: [ :index, :create, :show, :edit, :update ] do
        member do
          post :perform
        end
      end
    end
  end
  get "/admin", to: "admin/dashboard#index", as: :admin
  get "/admin/orders/:id/tracks", to: "admin/orders#track", as: :admin_order_track
  patch "/admin/order/:id/update_state/", to: "admin/orders#update_state", as: :order_state

  resources :contacts, only: [ :new, :create ]
  get "/frequently-asked-question", to: "public#faq", as: :faq
  get "/secure_shopping", to: "public#secure_shopping", as: :secure_shopping
  get "/coupon-code", to: "public#coupon", as: :coupon
  get "/return-policy", to: "public#return_policy", as: :return_policy
  get "/our-promise", to: "public#promise", as: :our_promise
  match "/dedicated-customer-support", to: "public#contact_us", via: [ :get, :post ], as: :contact_us
  get "/free-shipping-worldwide", to: "public#international", as: :international
  get "/safe_shopping_guarantee", to: "public#safe_shopping_guarantee", as: :safe_shopping_guarantee
  get "/about_us", to: "public#about_us", as: :about_us
  get "/privacy_policy", to: "public#privacy_policy", as: :privacy_policy
  get "/term_condition", to: "public#term_condition", as: :term_condition
  get "/my_account", to: "users#my_account"
  get "/cart", to: "public#cart"
  get "/p_checkout", to: "public#checkout"
  post "/email_subscription", to: "public#subscribe"
  post "/checkout", to: "checkout#check_coupon_code"

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :users
      get "home", to: "home#index"
      get "my_account", to: "users#my_account"
      resources :products, only: [ :index, :show ] do
        get "filters", on: :collection
        get "get_names", on: :collection
      end
      resources :wishlists, only: [ :index, :create ] do
        get :remove
      end
      resources :contacts, only: [ :create ]
      resources :orders, only: [ :index, :update, :show ] do
        post :populate, on: :collection
        post :current_cart, on: :collection
        post :detail, on: :collection
        post :current_state, on: :collection
        post :update_address, on: :collection
        post :update_order, on: :collection
        post :get_ship_address, on: :collection
        post :get_shipments, on: :collection
        post :get_payment_info, on: :collection
      end
      resources :reviews, only: [ :index, :create, :update, :destroy ]
      resources :shipments, only: [ :create, :update ] do
        member do
          put :ship
        end
      end
      resources :line_items do
        post :remove_item, on: :collection
      end

      post "/checkout/update_order/:state", to: "checkout#update_order", as: :update_checkout
    end
  end
end

app/models/image.rb
# == Schema Information
#
# Table name: images
#
#  id            :integer          not null, primary key
#  viewable_type :string
#  viewable_id   :integer
#  width         :integer
#  height        :integer
#  file_size     :integer
#  position      :integer
#  content_type  :string
#  file          :text
#  alt           :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#
# Indexes
#
#  index_images_on_viewable  (viewable_type,viewable_id)
#

class Image < ApplicationRecord
  belongs_to :viewable, polymorphic: true

  mount_uploader :file, Admin::ImageUploader
   validates_presence_of :file
end

app/controllers/admin/images_controller.rb
module Admin
  class ImagesController < BaseController
    before_action :set_product
    before_action :set_image, only: [:edit, :update, :destroy]

    def index
      @images = @product.images
    end

    def new
      @image = @product.images.build
    end

    def create
      @image = @product.images.build(image_params)
      respond_to do |format|
        if @image.save
          format.html { redirect_to admin_product_images_path(@product), notice: 'Image added to product successfully.' }
        else
          format.html { render :new }
        end
      end
    end

    def edit
    end

    def update
      respond_to do |format|
        if @image.update(image_params)
          format.html { redirect_to admin_product_images_path(@product), notice: 'Image updated successfully.' }
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      if @image.destroy
        flash[:notice] = 'Image deleted successfully.'
      else
        flash[:error] = 'Unable to deleted image.'
      end
      redirect_to admin_product_images_path(@product)
    end

    private

    def set_product
      @product = Product.friendly.find(params[:product_id])
    end

    def set_image
      @image = @product.images.find(params[:id])
    end

    def image_params
      params.require(:image).permit(:viewable_type, :viewable_id, :width,
                                    :height, :file_size, :position, :alt,
                                    :content_type, :file)
    end
  end
end

app/helpers/admin/images_helper.rb
module Admin::ImagesHelper
end

app/views/admin/images/_form.html.erb
<div data-hook="admin_image_form_fields" class="row">
  <div class="col-md-6">
    <div data-hook="file" class="form-group">
      <%= f.label :file, t(:filename) %>
      <%= f.file_field :file, required: true %>
      <span style="color: #00aced;">
        (<i>Recommended image size 600x600, minimum size 400x400 with 1:1.25 ratio if possible</i>)
      </span>
    </div>
  </div>
  <div data-hook="alt_text" class="col-md-6">
    <div class="form-group">
      <%= f.label :alt, t(:alt_text) %>
      <%= f.text_area :alt, :rows => 4, :class => 'form-control' %>
    </div>
  </div>
</div>

<script type="text/javascript">
    $(function () {
        $("#image_file").change(function () {
            readURL(this);
        });
    });

    function readURL(input) {
        if (input.files && input.files[0]) {
            var reader = new FileReader();

            reader.onload = function (e) {
                $('#image-upload-preview').attr('src', e.target.result);
            };

            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

app/views/admin/images/edit.html.erb
<% if @product.master? %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :images} %>
<% else %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :variants} %>
  <%= render partial: 'admin/variants/sidebar', locals: {current: :images} %>
<% end %>

<% content_for :page_title do %>
  <% if @product.master? %>
    <%= link_to @product.name, edit_admin_product_path(@product) %> /
  <% else %>
    <%= link_to @product.name, edit_admin_product_path(@product.product) %> /
    <%= link_to 'Variants', admin_product_variants_path(@product.product) %> /
    <%= link_to @product.code, edit_admin_product_variant_path(@product.product, @product) %> /
  <% end %>
  <%= link_to 'Images', admin_product_images_path(@product) %> /
  <%= link_to @image.file.present? ? @image.file.file.filename : 'Image', edit_admin_product_image_path(@product, @image) %> /
  <%= t(:edit_image) %>
<% end %>

<%= render partial: 'admin/shared/error_messages', locals: {target: @image} %>

<%= form_for [:admin, @product, @image], html: { multipart: true } do |f| %>
  <div data-hook="edit_image" class="panel panel-default">
    <div class="panel-heading">
      <h1 class="panel-title">
        <%= @image.file.file.filename if @image.file.present? %>
      </h1>
    </div>
    <div class="panel-body">
      <div class="form-group">
        <div data-hook="thumbnail" class="col-md-3 text-center">
          <%= f.label :file, t(:thumbnail) %>
          <%= link_to image_tag(@image.file.url(:small)), @image.file.url(:product) if @image.file.present? %>
        </div>
        <div class="col-md-9">
          <%= render partial: 'form', locals: { f: f } %>
        </div>

        <div class="form-actions" data-hook="buttons">
          <%= button t('actions.update'), 'save' %>
          <span class="or"><%= t(:or) %></span>
          <%= button_link_to t('actions.cancel'), admin_product_images_url(@product), id: 'cancel_link', icon: 'delete' %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<div style="margin-top: 15px; text-align: center;">
  <img src="" id="image-upload-preview"/>
</div>

app/views/admin/images/index.html.erb
<% if @product.master? %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :images} %>
<% else %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :variants} %>
  <%= render partial: 'admin/variants/sidebar', locals: {current: :images} %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to(t(:new_image), new_admin_product_image_url(@product), { class: "btn-success", icon: 'add', id: 'new_image_link' }) if can? :create, Image %>
<% end %>

<% content_for :page_title do %>
  <% if @product.master? %>
  <%= link_to @product.name, edit_admin_product_path(@product) %> / Images
  <% else %>
    <%= link_to @product.name, edit_admin_product_path(@product.product) %> /
    <%= link_to 'Variants', admin_product_variants_path(@product.product) %> /
    <%= link_to @product.code, edit_admin_product_variant_path(@product.product, @product) %> /
    Images
  <% end %>
<% end %>

<% if @images.any? %>
  <table class="table">
    <thead>
    <tr>
      <th> <%= t(:thumbnail) %> </th>
      <th><%= t(:alt_text) %></th>
      <th colspan="2"></th>
    </tr>
    </thead>

    <tbody>
    <% @images.each do |image| %>
      <tr>
        <td class="image">
          <%= link_to image_tag(image.file.url(:mini)), image.file.url(:product) if image.file.present? %>
        </td>
        <td><%= image.alt %></td>
        <td><%= link_to 'Edit', edit_admin_product_image_path(@product, image) %></td>
        <td><%= link_to 'Destroy', admin_product_image_path(@product, image), method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% else %>
  <div class="alert alert-info no-objects-found">
    <%= t(:no_resource_found, resource: 'Images') %>,
    <%= link_to t(:add_one), new_admin_product_image_path %>!
  </div>
<% end %>

app/views/admin/images/new.html.erb
<% if @product.master? %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :images} %>
<% else %>
  <%= render partial: 'admin/products/sidebar', locals: {current: :variants} %>
  <%= render partial: 'admin/variants/sidebar', locals: {current: :images} %>
<% end %>

<%= render partial: 'admin/shared/error_messages', locals: {target: @image} %>

<% content_for :page_title do %>
  <% if @product.master? %>
    <%= link_to @product.name, edit_admin_product_path(@product) %> /
  <% else %>
    <%= link_to @product.name, edit_admin_product_path(@product.product) %> /
    <%= link_to 'Variants', admin_product_variants_path(@product.product) %> /
    <%= link_to @product.code, edit_admin_product_variant_path(@product.product, @product) %> /
  <% end %>
  <%= link_to 'Images', admin_product_images_path(@product) %> /
  <%= t(:new_image) %>
<% end %>

<%= form_for [:admin, @product, @image], html: {multipart: true} do |f| %>
  <fieldset data-hook="new_image">
    <%= render 'form', f: f %>

    <div class="form-actions" data-hook="buttons">
      <%= button t('actions.create'), 'save' %>
      <span class="or"><%= t(:or) %></span>
      <%= button_link_to t('actions.cancel'), admin_product_images_url(@product), icon: 'delete', id: 'cancel_link' %>
    </div>
  </fieldset>
<% end %>

<div style="margin-top: 15px; text-align: center;">
  <img src="" id="image-upload-preview"/>
</div>